package com.classing.wear.timetable.ui.theme

import androidx.compose.ui.graphics.Color

val IndigoPrimary = Color(0xFFBAC3FF)
val IndigoOnPrimary = Color(0xFF232C5E)
val IndigoPrimaryContainer = Color(0xFF4E578B)
val IndigoOnPrimaryContainer = Color(0xFFC9CFFF)
val IndigoSecondary = Color(0xFFBAC3FF)
val IndigoOnSecondary = Color(0xFF08218A)
val IndigoSecondaryContainer = Color(0xFF2C3EA3)
val IndigoOnSecondaryContainer = Color(0xFFA8B4FF)
val IndigoTertiary = Color(0xFFFFB784)
val IndigoOnTertiary = Color(0xFF502500)
val IndigoBackground = Color(0xFF000000)
val IndigoOnBackground = Color(0xFFE2E2E2)
val IndigoSurface = Color(0xFF131313)
val IndigoOnSurface = Color(0xFFE2E2E2)
val IndigoSurfaceVariant = Color(0xFF353535)
val IndigoOnSurfaceVariant = Color(0xFFC5C5D4)
val IndigoOutline = Color(0xFF8F909E)
val IndigoOutlineVariant = Color(0xFF454652)
val IndigoSurfaceContainerLow = Color(0xFF1B1B1B)
val IndigoSurfaceContainer = Color(0xFF1F1F1F)
val IndigoSurfaceContainerHigh = Color(0xFF2A2A2A)
val IndigoError = Color(0xFFFFB4AB)
